// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SHOOTERPID_H
#define SHOOTERPID_H
#include "Commands/PIDSubsystem.h"
#include "WPILib.h"
#include "../AHRS.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ShooterPID: public PIDSubsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> shooterRight;
		std::shared_ptr<CANTalon> shooterLeft;
		std::shared_ptr<CANTalon> feeder;

	double m_setRPM;

public:
	ShooterPID();
	void InitDefaultCommand();
	void SetShooterSpeed(double RPM);
		void PrintShooterRPM();
		void Fire_smiley();
		void StopFeeder();
		void StartFeeder();
		//void UpdateSecondary();
		void KillShooterSpeed();
	void ResetEncoder();

};

#endif
