// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Blue_AutoShootGearShoot.h"

#include "Fire.h"
#include "SetShooterSpeed.h"
#include "WaveWait.h"
#include "AutoDrive.h"
#include "AutoCrab.h"
#include "ZeroYaw.h"
#include "ResetEncoders.h"
#include "SetFeederOff.h"
#include "SetIntakeOff.h"
#include "AutoRotate.h"
#include "GearEject.h"
#include "GearUneject.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Blue_AutoShootGearShoot::Blue_AutoShootGearShoot() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
	//
	//shoot
	AddSequential(new ResetEncoders());
	AddSequential(new ZeroYaw());
	AddSequential(new AutoCrab(-10, 0, -1, 2.5));
	AddSequential(new AutoRotate(-8, -1, 1));
	AddSequential(new SetShooterSpeed(857, 1.5));
	AddSequential(new Fire(2));
	AddSequential(new SetShooterSpeed(0, .25));


	//drive to peg
	AddParallel(new SetFeederOff());
	AddParallel(new SetIntakeOff());
	//AddSequential(new ZeroYaw());
	//AddSequential(new ResetEncoders());
	//AddSequential(new AutoDrive (20, 0, .7));
//	AddSequential(new AutoRotate(180, 1, 2));
	//AddSequential(new ZeroYaw());
	//AddSequential(new ResetEncoders());
	//AddSequential(new AutoDrive(10, 0, .7));
	AddSequential(new ZeroYaw());
	AddSequential(new ResetEncoders());
	AddSequential(new AutoDrive(160, 150, .7));
	AddSequential(new WaveWait(.25));
	AddSequential(new ResetEncoders());
	AddSequential(new ZeroYaw());
	AddSequential(new AutoCrab(5, 0, 1, 2));
	AddSequential(new WaveWait(.5));

	//eject gear
	AddSequential(new GearEject());
	AddSequential(new WaveWait(.5));
	AddSequential(new ResetEncoders());
	AddSequential(new ZeroYaw());
	AddSequential(new AutoDrive(-13, 0, -.7));
	AddSequential(new GearUneject());
	AddSequential(new ZeroYaw());
	AddSequential(new ResetEncoders());

	//drive to hopper
	AddSequential(new AutoRotate(120, 1, 1.5));
	AddSequential(new AutoCrab(-300, 0, -1, 2.5));



	//91 in y direction
	//AddSequential(new AutoDrive());
	//AddSequential(new WaveWait(5));
	//AddSequential(new AutoDrive());
//	AddSequential(new Fire());
//	AddParallel(new WaveWait(5));


    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
