// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Blue_Auto40kPaGear.h"
#include "Fire.h"
#include "SetShooterSpeed.h"
#include "WaveWait.h"
#include "AutoDrive.h"
#include "GearEject.h"
#include "AutoGearAngle.h"
#include "AutoRotate.h"
#include "ZeroYaw.h"
#include "ResetEncoders.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Blue_Auto40kPaGear::Blue_Auto40kPaGear() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:

	//Drive to Gear Peg
	//Eject Gear
	//Turn
	//Drive to Hopper
	//Drive to Boiler
	//Shoot

	AddSequential(new AutoGearAngle());
	//AddSequential(new AutoRotate(0, .2, 1.0));
	AddSequential(new ResetEncoders());
	AddSequential(new AutoRotate(-40, .2, 1.5));
	AddSequential(new WaveWait(.5));
	AddSequential(new ZeroYaw());
	AddSequential(new ResetEncoders());
	AddSequential(new AutoDrive(53, -9, .7));

    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
