// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Red_Auto40kPaGear.h"
#include "SetShooterSpeed.h"
#include "Fire.h"
#include "WaveWait.h"
#include "GearEject.h"
#include "AutoDrive.h"
#include "ZeroYaw.h"
#include "GearUneject.h"
#include "Red_AutoGearAngle.h"
#include "AutoRotate.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Red_Auto40kPaGear::Red_Auto40kPaGear() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR



	AddSequential(new Red_AutoGearAngle());
//	AddSequential(new AutoRotate(40, .2, 1.5));//not tested from here on 3/4/17
////	AddSequential(new WaveWait(.5));
//	AddSequential(new ZeroYaw());
//	AddSequential(new AutoDrive(53, 9, -.7));

     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
