
#ifndef TELEROTATE_H
#define TELEROTATE_H

#include "Commands/CommandGroup.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class TeleRotate: public CommandGroup {
public:

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	TeleRotate();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

private:

};

#endif
